services:
  jupyter:
    build: .
    ports:
      - 8888:8888
    user: root
    environment:
      - GRANT_SUDO=yes
      - NB_UID=${USER_ID:-1000}
      - NB_GID=${USER_GID:-1000}
      - DOCKER_STACKS_JUPYTER_CMD=notebook
    command: start-notebook.py --IdentityProvider.token='' --ip=0.0.0.0 --NotebookApp.default_url=/notebooks/work/analysis.ipynb
    volumes:
      - ./work:/home/jovyan/work:cached
